version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-67-106.compute-1.amazonaws.com
            database: ddbklka9i7hgi
            user: uiwbofikntnjok
            password: 2ba45724cef7a8dfb26add70418959fa8bccf4d867a4184aea97f62c8b270508
            rawAccess: true
            port: '5432'
            migrations: true