export const COMMENT = 'COMMENT'
export const POST = 'POST'
export const USER = 'USER'
export const CREATED = 'CREATED'
export const DELETED = 'DELETED'
export const UPDATED = 'UPDATED'
export const PUBLISHED = 'PUBLISHED'
export const UNPUBLISHED = 'UNPUBLISHED'
